version: "3.9"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080
      - NEXT_PUBLIC_KEYCLOAK_REALM=your-realm
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=nextjs-client
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
